name: Feature Request
description: Suggest a new feature or enhancement for PayBru
title: "[Feature]: "
labels: ["enhancement", "needs-review"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've also considered...
    validations:
      required: false

  - type: dropdown
    id: user-type
    attributes:
      label: Who would benefit from this feature?
      description: Select all that apply
      multiple: true
      options:
        - Community Creators
        - Community Members
        - Administrators
        - Developers/Integrators
        - All Users
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking workflow)
        - High (Would significantly improve experience)
        - Medium (Nice to have)
        - Low (Minor improvement)
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. As a creator, I would use this to...
        2. This would help members by...
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, wireframes, or examples from other platforms
      placeholder: Drag and drop images here...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for similar feature requests before creating this one
          required: true
        - label: I have provided clear use cases for this feature
          required: true

